version: "3.1"
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=zoup
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: