# Generated by Django 4.1.5 on 2023-01-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="family",
        ),
        migrations.AddField(
            model_name="profile",
            name="_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="get_members",
                to="Items.family",
            ),
        ),
    ]
