# Generated by Django 4.1.5 on 2023-01-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0002_remove_profile_family_profile__family"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="Items.category",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="Items.family",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="chat_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
