# Generated by Django 4.1.7 on 2023-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Items", "0003_profile_telegram_name_alter_keyword_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="message_id",
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
