# Generated by Django 4.1.7 on 2023-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Items", "0004_product_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="chat_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
