# Generated by Django 4.1.7 on 2023-03-14 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Items", "0005_alter_profile_chat_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="chat_id",
            new_name="_chat_id",
        ),
    ]
