# Generated by Django 4.1.3 on 2022-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="chat_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
