# Generated by Django 4.1.7 on 2023-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Items", "0006_rename_chat_id_profile__chat_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="_chat_id",
            new_name="chat_id",
        ),
    ]
